// Reviewed grammar policy. Adding a native rule never implicitly enables its
// diagnostics or replacement actions in the editor.
export const writingGrammarVersion = 'harper-0.1.0-curated-1+figaro-8';
const rule = (title, fixes = true, context = 'block') => Object.freeze({ title, fixes, context });
export const writingGrammarRules = Object.freeze({
    'Harper.BetterOffWith': rule('Check “better off with”'),
    'Harper.SimplePastToPastParticiple': rule('Check past participle'),
    'Harper.SupposedTo': rule('Check “supposed to”'),
    'Harper.TheMy': rule('Review doubled determiner', false),
    'Harper.TheMy2': rule('Review doubled determiner', false),
    'Harper.DespiteOf': rule('Check “despite”', false),
    'Harper.IsBeenAuxSequence': rule('Check auxiliary verbs'),
    'Harper.AnAnother': rule('Check “another”'),
    'Harper.AnotherAn': rule('Check “another”'),
    'Harper.TheAnother': rule('Check “the other” or “another”'),
    'Harper.SomeOfThe': rule('Check “some of the”'),
    'Harper.EachOthersPossessive': rule('Check reciprocal possessive'),
    'Harper.SomebodyElses': rule('Check “somebody else’s”'),
    'Harper.ForTheNthTime': rule('Review missing article', false),
    'Harper.WillNonLemma': rule('Review verb after “will” or “shall”', false),
    'FigaroGrammar.PronounVerbAgreement': rule('Check pronoun and verb agreement'),
    'FigaroGrammar.IAmAgreement': rule('Check “I am”'),
    'FigaroGrammar.PronounInflectionBe': rule('Check subject and “be” agreement'),
    'FigaroGrammar.InflectedVerbAfterTo': rule('Check verb after “to”'),
    'FigaroGrammar.ModalOf': rule('Check “have” after modal verb'),
    'FigaroGrammar.MissingTo': rule('Check missing “to”'),
    'FigaroGrammar.DidPast': rule('Check verb after “did”'),
    'FigaroGrammar.DoubleModal': rule('Review adjacent modal verbs', false),
    'FigaroGrammar.ModalBeAdjective': rule('Check missing “be”'),
    'FigaroGrammar.OughtToBe': rule('Check “ought to be”'),
    'FigaroGrammar.LetToDo': rule('Check verb after “let”'),
    'FigaroGrammar.ThereIsAgreement': rule('Check “there is/are” agreement'),
    'FigaroGrammar.OneOfTheSingular': rule('Check plural after “one of the”'),
    'FigaroGrammar.MassNouns': rule('Check uncountable noun'),
    'FigaroGrammar.CriteriaPhenomena': rule('Check “criterion/criteria” or “phenomenon/phenomena”'),
    'FigaroGrammar.ItsPossessive': rule('Check possessive “its”'),
    'FigaroGrammar.ItsContraction': rule('Check contraction “it’s”'),
    'FigaroGrammar.ThereToTheir': rule('Check “there/their”'),
    'FigaroGrammar.TheirToThere': rule('Check “their/there”'),
    'FigaroGrammar.TheirToTheyre': rule('Check contraction “they’re”'),
    'FigaroGrammar.TheyreToTheir': rule('Check possessive “their”'),
    'FigaroGrammar.PossessiveYour': rule('Check possessive “your”'),
    'FigaroGrammar.YourPredicateAdjective': rule('Check contraction “you’re”'),
    'FigaroGrammar.ThenThan': rule('Check “then/than”'),
    'FigaroGrammar.ToTwoToo': rule('Check “to/too”'),
    'FigaroGrammar.NounVerbConfusion': rule('Check related noun and verb'),
    'FigaroGrammar.WereWhere': rule('Check “were/where”'),
    'FigaroGrammar.Everyday': rule('Check “everyday/every day”'),
    'FigaroGrammar.Discuss': rule('Check “discuss” construction'),
    'FigaroGrammar.AskNoPreposition': rule('Check object after “ask” or “tell”'),
    'FigaroGrammar.AllowTo': rule('Check “allow” construction'),
    'FigaroGrammar.WorthToDo': rule('Check verb after “worth”'),
    'FigaroGrammar.ElsePossessive': rule('Check possessive “else’s”'),
    'FigaroGrammar.SubjectPronoun': rule('Check compound subject'),
    'FigaroGrammar.CompoundSubjectI': rule('Check subject pronoun “I”'),
    'FigaroGrammar.HavePronoun': rule('Check “have” in questions'),
    'FigaroGrammar.DoIAdjective': rule('Check “am I” in questions'),
    'FigaroGrammar.MultipleSequentialPronouns': rule('Review adjacent pronouns', false),
    'FigaroGrammar.PluralDecades': rule('Check plural decade'),
    'FigaroGrammar.LookingForwardTo': rule('Check verb after “look forward to”'),
    'FigaroGrammar.InterestedIn': rule('Check “interested in”'),
    'FigaroGrammar.SinceDuration': rule('Check “since” with a duration'),
    'FigaroGrammar.AdjectiveDoubleDegree': rule('Check repeated comparison'),
    'FigaroGrammar.AllIntentsAndPurposes': rule('Check “all intents and purposes”'),
    'FigaroGrammar.BareInMind': rule('Check “bear in mind”'),
    'FigaroGrammar.MootPoint': rule('Check “moot point”'),
    'FigaroGrammar.WaistWaste': rule('Check “waist/waste”'),
    'FigaroGrammar.TheWhetherWeather': rule('Check “whether/weather”'),
    'FigaroGrammar.Itself': rule('Check “itself”'),
    'FigaroGrammar.Misunderstood': rule('Check “misunderstood”'),
    'FigaroGrammar.CorrectNumberSuffix': rule('Check ordinal number ending'),
    'FigaroGrammar.CapitalizePersonalPronouns': rule('Capitalize “I”'),
    'FigaroGrammar.CommaFixes': rule('Check comma spacing'),
    // These native decisions establish their own bounded context. Countable
    // amount spans its entire phrase; clause-boundary advice never offers Apply.
    'FigaroGrammar.CountableAmount': rule('Check countable quantity', true, 'local'),
    'FigaroGrammar.CommaSplice': rule('Review comma between clauses', false, 'local'),
    'FigaroGrammar.HyphenateNumberDay': rule('Check number-day hyphen'),
    'FigaroGrammar.IfWouldve': rule('Review past conditional', false),
    'FigaroGrammar.AMeansToAnEnd': rule('Check “a means to an end”'),
    'FigaroGrammar.AdNauseam': rule('Check “ad nauseam”'),
    'FigaroGrammar.Albeit': rule('Check “albeit”'),
    'FigaroGrammar.AllOfASudden': rule('Check “all of a sudden”'),
    'FigaroGrammar.AsFollows': rule('Check “as follows”'),
    'FigaroGrammar.AtAllCosts': rule('Check “at all costs”'),
    'FigaroGrammar.BatedBreath': rule('Check “bated breath”'),
    'FigaroGrammar.BeckAndCall': rule('Check “beck and call”'),
    'FigaroGrammar.CaseInPoint': rule('Check “case in point”'),
    'FigaroGrammar.FreeRein': rule('Check “free rein”'),
    'FigaroGrammar.InLieuOf': rule('Check “in lieu of”'),
    'FigaroGrammar.InOfItself': rule('Check “in and of itself”'),
    'FigaroGrammar.OnTheSpurOfTheMoment': rule('Check “on the spur of the moment”'),
    'FigaroGrammar.PeaceOfMind': rule('Check “peace of mind”'),
    'FigaroGrammar.PerSe': rule('Check “per se”'),
    'FigaroGrammar.SneakPeekPreview': rule('Check “sneak peek”'),
    'FigaroGrammar.WhetYourAppetite': rule('Check “whet your appetite”'),
    'FigaroGrammar.Ado': rule('Check “without further ado”'),
    'FigaroGrammar.DigestiveTract': rule('Check “digestive tract”'),
    'FigaroGrammar.ExplanationMark': rule('Check “exclamation mark”'),
    'FigaroGrammar.ExtendOrExtent': rule('Check “extend/extent”'),
    'FigaroGrammar.GetUsedTo': rule('Check “get used to”'),
    'FigaroGrammar.GrindToAHalt': rule('Check “grind to a halt”'),
    'FigaroGrammar.InThisThatRegard': rule('Check “in this/that regard”'),
    'FigaroGrammar.InflectionPoint': rule('Check “inflection point”'),
    'FigaroGrammar.LookForwardTo': rule('Check “look forward to”'),
    'FigaroGrammar.MakeDoWith': rule('Check “make do with”'),
    'FigaroGrammar.ResponsibilityFor': rule('Check “responsibility for”'),
    'FigaroGrammar.WreakHavoc': rule('Check “wreak havoc”'),
    'FigaroGrammar.WroteToRote': rule('Check “by rote”'),
    'FigaroGrammar.GetRidOf': rule('Check “get rid of”'),
    'FigaroGrammar.StatuteOfLimitations': rule('Check “statute of limitations”'),
    'FigaroGrammar.TrialAndError': rule('Check “trial and error”'),
    'FigaroGrammar.ThanksALot': rule('Check “thanks a lot”'),
    'FigaroGrammar.InAnIdealWorld': rule('Check “in an ideal world”'),
    'FigaroGrammar.OutOfSync': rule('Check “out of sync”'),
    'FigaroGrammar.Furthermore': rule('Check “furthermore”'),
    'FigaroGrammar.Meanwhile': rule('Check “meanwhile”'),
    'FigaroGrammar.Therefore': rule('Check “therefore”'),
    'FigaroGrammar.Misunderstand': rule('Check “misunderstand”'),
    'FigaroGrammar.Misused': rule('Check “misused”'),
    'FigaroGrammar.DoubleEdgedSword': rule('Check “double-edged sword”'),
    'FigaroGrammar.BackhandedCompliment': rule('Check “backhanded compliment”'),
    'FigaroGrammar.AccuseOf': rule('Check “accuse of”'),
    'FigaroGrammar.AspireTo': rule('Check “aspire to”'),
    'FigaroGrammar.GoodAt': rule('Check “good at”'),
    'FigaroGrammar.FascinatedBy': rule('Check “fascinated by”'),
    'FigaroGrammar.JealousOf': rule('Check “jealous of”'),
    'FigaroGrammar.PassionateAbout': rule('Check “passionate about”'),
    'FigaroGrammar.TakeCareOf': rule('Check “take care of”'),
    'FigaroGrammar.TakePrideIn': rule('Check “take pride in”'),
    'FigaroGrammar.ReasonForDoing': rule('Check “reason for”'),
    'FigaroGrammar.InFavourOfDoing': rule('Check “in favour of”'),
    'FigaroGrammar.CureFor': rule('Check “cure for”'),
    'FigaroGrammar.ExceptOf': rule('Check “except of”'),
    'FigaroGrammar.TakeALookTo': rule('Check “take a look to”'),
    'FigaroGrammar.AwareOf': rule('Check “aware of”'),
    'FigaroGrammar.BewareOf': rule('Check “beware of”'),
    'FigaroGrammar.CuriousAbout': rule('Check “curious about”'),
    'FigaroGrammar.InspiredBy': rule('Check “inspired by”'),
    'FigaroGrammar.InsteadOf': rule('Check “instead of”'),
    'FigaroGrammar.LaughOfAt': rule('Check “laugh at”'),
    'FigaroGrammar.SimilarLike': rule('Check “similar like”'),
    'FigaroGrammar.AwaitFor': rule('Check “await for”'),
    'FigaroGrammar.AsOpposedTo': rule('Check “as opposed to”'),
    'FigaroGrammar.DueDiligence': rule('Check “due diligence”'),
    'FigaroGrammar.EnMasse': rule('Check “en masse”'),
    'FigaroGrammar.EnRoute': rule('Check “en route”'),
    'FigaroGrammar.ForALongTime': rule('Check “for a long time”'),
    'FigaroGrammar.HalfAnHour': rule('Check “half an hour”'),
    'FigaroGrammar.InHindsight': rule('Check “in hindsight”'),
    'FigaroGrammar.InTheSameVein': rule('Check “in the same vein”'),
    'FigaroGrammar.OneAndTheSame': rule('Check “one and the same”'),
    'FigaroGrammar.OnceInAWhile': rule('Check “once in a while”'),
    'FigaroGrammar.RulesOfThumb': rule('Check “rules of thumb”'),
    'FigaroGrammar.PointsOfView': rule('Check “points of view”'),
    'FigaroGrammar.PassersBy': rule('Check “passersby”'),
    'FigaroGrammar.StateOfTheArt': rule('Check “state of the art”'),
    'FigaroGrammar.OneFellSwoop': rule('Check “one fell swoop”'),
    'FigaroGrammar.PiqueInterest': rule('Check “pique interest”'),
    'FigaroGrammar.QuiteQuiet': rule('Check “quite quiet”'),
    'FigaroGrammar.PrincipleToPrincipalRoleNoun': rule('Check “principle/principal”'),
    'FigaroGrammar.ToLoseTooLoose': rule('Check “lose/loose”'),
    'FigaroGrammar.BoarderBorder': rule('Check “boarder/border”'),
    'FigaroGrammar.SeamToSeem': rule('Check “seam/seem”'),
    'FigaroGrammar.DoesOrDose': rule('Check “does/dose”'),
    'FigaroGrammar.SafeToSave': rule('Check verb “save”'),
    'FigaroGrammar.SaveToSafe': rule('Check adjective “safe”'),
    'FigaroGrammar.WasAloud': rule('Check “aloud/allowed”'),
    'FigaroGrammar.SpinalChord': rule('Check “chord/cord”'),
    'FigaroGrammar.HopHope': rule('Check “hop/hope”'),
    'FigaroGrammar.Notwithstanding': rule('Check “notwithstanding”'),
    'FigaroGrammar.Henceforth': rule('Check “henceforth”'),
    'FigaroGrammar.Whereas': rule('Check “whereas”'),
    'FigaroGrammar.Beforehand': rule('Check “beforehand”'),
    'FigaroGrammar.Alongside': rule('Check “alongside”'),
    'FigaroGrammar.EveryTime': rule('Check “every time”'),
    'FigaroGrammar.OvertimeCompoundNoun': rule('Check “overtime” modifier'),
    'FigaroGrammar.LetsConfusion': rule('Check “lets/let’s”'),
    'FigaroGrammar.DoMistake': rule('Check “make a mistake”'),
    'FigaroGrammar.FriendOfMe': rule('Check possessive after “friend of”'),
    'FigaroGrammar.HaveAHardTime': rule('Check “have a hard time”'),
    'FigaroGrammar.HowDoesCompared': rule('Check verb after “do/does”'),
    'FigaroGrammar.NounSubjectAgreement': rule('Check noun and verb agreement'),
    'FigaroGrammar.UseToUsedTo': rule('Check “used to”'),
});

export const writingGrammarKinds = Object.freeze(Object.fromEntries(Object.keys(writingGrammarRules)
    .map(name => [name, `grammar.${name.toLowerCase()}`])));

// Masking a quote, code span or technical token can make unrelated words look
// adjacent. Withhold context-sensitive grammar for that entire prose block.
export function createWritingGrammarContext(projection) {
    const eligible = new Map();
    return (from, to) => {
        if (from < 0 || to <= from) return false;
        const region = projection.regions?.find(item => item.start <= from && item.end >= to);
        if (!region) return false;
        if (!eligible.has(region)) {
            let safe = true;
            for (let i = region.start; i < region.end; i++) {
                const unit = projection.units[i];
                if (!unit || unit.from < 0 || unit.hidden) { safe = false; break; }
            }
            eligible.set(region, safe);
        }
        return eligible.get(region);
    };
}

export function writingGrammarReplacements(alert) {
    if (!writingGrammarRules[alert.Check]?.fixes || alert.Action?.Name !== 'replace' || !Array.isArray(alert.Action.Params)) return [];
    return [...new Set(alert.Action.Params)].filter(value => typeof value === 'string' && value.length > 0 && value.length <= 160
        && [...value].every(char => char.codePointAt(0) >= 32 && char.codePointAt(0) !== 127)).slice(0, 4);
}
