const mockState={openTabs:[{id:'note',type:'file',path:'Note.md'}],activeTabId:'note'};
const mockDoc={toString:()=> 'First.\n\nSecond.',eq(other){return this.toString()===other.toString();}};
const mockView={isDestroyed:false,dom:document.createElement('div'),state:{doc:mockDoc,field:()=>({enabled:false,events:[]})},dispatch:jest.fn(),focus:jest.fn()};
const mockReview={select:jest.fn(),changed:jest.fn(),refresh:jest.fn(),retry:jest.fn(),destroy:jest.fn()};
let mockPorts,mockOpen,mockRestore,mockClose;
jest.mock('../frontend/js/editor.js',()=>({getEditorDocumentTabId:()=> 'note',getEditorView:()=>mockView}));
jest.mock('../frontend/js/state.js',()=>({getState:key=>mockState[key]}));
jest.mock('../frontend/js/activityGutter.js',()=>({activityState:{},setActivityData:{of:value=>value},currentActivityPassages:()=>[{from:0,to:6,events:[]},{from:8,to:15,events:[]}],configureActivityGutter:({open})=>{mockOpen=open;}}));
jest.mock('../frontend/js/usecases/activityReview.js',()=>({createActivityReview:ports=>{mockPorts=ports;return mockReview;}}));
jest.mock('../frontend/js/activityWorkerClient.js',()=>({createActivityWorker:()=>({ready:Promise.resolve(),destroy:jest.fn()})}));
jest.mock('../frontend/js/rightPaneCoordinator.js',()=>({claimRightPane:jest.fn(),registerRightPaneMode:(_mode,close,open)=>{mockClose=close;mockRestore=open;}}));
jest.mock('../frontend/js/rightSidebarState.js',()=>({setRightSidebarOpen:(element,open)=>element.classList.toggle('open',open)}));
import { initActivity,setActivityDatesEnabled } from '../../../frontend/js/activity.js';
const settle=async()=>{await Promise.resolve();await Promise.resolve();};
test('Activity restores the selected passage after a Settings detour even with margin dates hidden, and rejects queued publications for another owner',async()=>{
 document.body.innerHTML='<aside id="right-sidebar"><h2 id="right-sidebar-title"></h2><div id="history-content"></div></aside><div id="right-sidebar-resizer"></div>';
 await initActivity(); setActivityDatesEnabled(true); await settle();
 mockOpen(mockView,{from:0,to:6},null);
 mockPorts.publish({key:'note',status:'ready',source:mockDoc.toString()});await settle();
 expect(document.querySelector('.activity-context').textContent).toBe('1 passage');
 setActivityDatesEnabled(false);await settle();
 mockState.activeTabId='settings';mockClose({restoreFocus:false});document.dispatchEvent(new Event('active-tab-changed'));await settle();
 mockState.activeTabId='note';document.dispatchEvent(new Event('active-tab-changed'));mockRestore();
 mockPorts.publish({key:'note',status:'ready',source:mockDoc.toString()});await settle();
 expect(document.querySelector('.activity-context').textContent).toBe('1 passage');
 expect(document.querySelector('#right-sidebar').dataset.mode).toBe('activity');
 mockView.dispatch.mockClear();mockPorts.publish({key:'note',status:'ready',source:mockDoc.toString()});
 mockState.activeTabId='settings';await settle();expect(mockView.dispatch).not.toHaveBeenCalled();
 window.dispatchEvent(new Event('beforeunload'));
});
