/** Canonical JavaScript surface exported by the bound desktop App facade. */
export const BACKEND_METHODS = Object.freeze([
    'AutoCommitLoad',
    'AutoCommitSave',
    'AutoSaveLoad',
    'AutoSaveSave',
    'ChangeLinkStyle',
    'CodeFontSave',
    'CommitCurrentFile',
    'CopyExternalPaths',
    'CopyPath',
    'CreateDirectory',
    'CreateFile',
    'CreateInboxNote',
    'CreateStarterPrintStylesheet',
    'CreateUpgradedPrintStylesheet',
    'DeleteKanbanColumn',
    'DeletePath',
    'EditorNavigationLoad',
    'EditorNavigationSave',
    'ExportPDF',
    'FileHasUncommittedChanges',
    'FontSave',
    'GetApplicationVersion',
    'GetCalendarMonthData',
    'GetCalendarTimelineData',
    'GetCommitCount',
    'GetDueTaskSummary',
    'GetFileActivity',
    'GetFileHistory',
    'GetFileTree',
    'GetFileTreeStyles',
    'GetFileVersion',
    'GetHomeTasks',
    'GetKanbanBoard',
    'GetKanbanColumns',
    'GetLaunchExternalFiles',
    'GetLinkedNotesForDate',
    'GetOSUsername',
    'GetRecentlyDeleted',
    'GetTaskSchedules',
    'GetTasksDueOnDate',
    'GetThemeCSS',
    'GetThemes',
    'GetTodayLink',
    'GetTomorrowLink',
    'GetVaultFileIssues',
    'GetVaultGraph',
    'GetVaultHealth',
    'GetVaultLoadStatus',
    'GetYesterdayLink',
    'LineNumbersLoad',
    'LineNumbersSave',
    'LinkStyleLoad',
    'LinkUnlinkedMention',
    'LoadSession',
    'MarkdownLintLoad',
    'MarkdownLintSave',
    'MergeDirectory',
    'MergeExternalPaths',
    'MergeNotes',
    'MovePath',
    'OpenLaunchExternalFile',
    'OpenWithDefaultApplication',
    'PDFBrowserChoose',
    'PDFBrowserClear',
    'PDFBrowserLoad',
    'PreviewRenamePath',
    'ReadDiagram',
    'ReadFile',
    'ReadLaunchExternalFile',
    'RecheckVaultFileIssues',
    'RemoveTagFromTask',
    'RenameKanbanColumn',
    'RenamePath',
    'RenamePathWithLinkUpdates',
    'RestoreRecentlyDeleted',
    'RevealInExplorer',
    'RevealLaunchExternalFile',
    'SaveClipboardImage',
    'SaveFile',
    'SaveLaunchExternalFile',
    'SaveSession',
    'SearchBacklinks',
    'SearchFiles',
    'SearchNotes',
    'SearchUnlinkedMentions',
    'SetColumnColor',
    'SetFileTreePinned',
    'SetFileTreeStyle',
    'SetKanbanCardOrder',
    'SetTaskDueDate',
    'SetTaskSchedule',
    'SpellcheckLoad',
    'SpellcheckSave',
    'SpellingDictionaryLoad',
    'SpellingDictionaryAdd',
    'StartVaultLoad',
    'TabSizeLoad',
    'TabSizeSave',
    'ThemeLoad',
    'ThemeSave',
    'UpdateTaskTag',
    'VimLoad',
    'VimRevealBlocksLoad',
    'VimRevealBlocksSave',
    'VimSave',
    'VimVisualRowsLoad',
    'VimVisualRowsSave',
    'WindowCaptureState',
    'WindowClose',
    'WindowGetPosition',
    'WindowGetSize',
    'WindowMaximize',
    'WindowMinimize',
    'WindowSetPosition',
    'WindowSetSize',
    'WindowSetTitle',
    'WindowStartResize',
    'WritingInitialize',
    'WritingAnalyze',
    'WritingCancel',
    'WritingDecisionsLoad',
    'WritingDecisionsChange',
    'WritingLensesLoad',
    'WritingLensesSave',
    'WritingLensesApplyAll',
]);

export function missingBackendMethods(api) {
    return BACKEND_METHODS.filter(name => typeof api?.[name] !== 'function');
}

export function assertBackendContract(api, label = 'Desktop backend') {
    const missing = missingBackendMethods(api);
    if (missing.length) {
        throw new TypeError(`${label} is missing: ${missing.join(', ')}`);
    }
    return api;
}

/** Build complete browser/test doubles from the same facade contract. */
export function createBackendStub(overrides = {}, fallback = () => async () => undefined) {
    return Object.fromEntries(BACKEND_METHODS.map(name => [
        name,
        typeof overrides[name] === 'function' ? overrides[name] : fallback(name),
    ]));
}
